#!/usr/bin/env bash
#
# setup-root-ca.sh
# Step 1 of a Root CA / Intermediate CA PKI hierarchy.
#
# Operates on an ALREADY-EXISTING ./ca/openssl.cnf (the one that uses
# ${ENV::CA_COUNTRY} etc. substitutions) rather than generating one, so the
# config stays checked into your repo and under version control.
#
# Usage:
#   CA_COUNTRY=SN CA_STATE=Dakar CA_LOCALITY=Dakar \
#   CA_ORG="My Organization" CA_ORG_UNIT="My Organization Root CA" \
#   CA_COMMON_NAME="My Organization Root CA" \
#   [CA_EMAIL=pki@example.com] \
#   ./setup-root-ca.sh [ca-dir]
#
# ca-dir defaults to "./ca" and must already contain openssl.cnf.
#
# All six identity vars above are REQUIRED except CA_EMAIL. The script also
# writes <ca-dir>/ca-defaults.env, containing just the fields that MUST be
# identical between root and intermediate (country/state/locality/org) —
# policy_strict in openssl.cnf enforces that match when the root signs the
# intermediate's CSR. setup-intermediate-ca.sh sources that file
# automatically, so you only ever type those four values once.

set -euo pipefail

ROOT_CA_DIR="${1:-./ca}"
export ROOT_CA_DIR
echo "[*] Using existing CA directory: ${ROOT_CA_DIR}"
if [ ! -d "${ROOT_CA_DIR}" ]; then
  echo "[!] Directory does not exist: ${ROOT_CA_DIR}" >&2
  exit 1
fi

cd "${ROOT_CA_DIR}"
CA_CONFIG="./openssl.cnf"

if [ ! -s "${CA_CONFIG}" ]; then
  echo "[!] Missing or empty OpenSSL config file: ${CA_CONFIG}" >&2
  exit 1
fi

# -----------------------------------------------------------------------------
# 0. Required subject values for the root certificate
# -----------------------------------------------------------------------------
for required_var in CA_COUNTRY CA_STATE CA_LOCALITY CA_ORG CA_ORG_UNIT CA_COMMON_NAME; do
  if [ -z "${!required_var:-}" ]; then
    echo "[!] Required environment variable ${required_var} is not set." >&2
    echo "    Example:" >&2
    echo "      CA_COUNTRY=SN CA_STATE=Dakar CA_LOCALITY=Dakar \\" >&2
    echo "      CA_ORG='My Organization' CA_ORG_UNIT='My Organization Root CA' \\" >&2
    echo "      CA_COMMON_NAME='My Organization Root CA' ./setup-root-ca.sh" >&2
    exit 1
  fi
done
export CA_COUNTRY CA_STATE CA_LOCALITY CA_ORG CA_ORG_UNIT CA_COMMON_NAME
CA_EMAIL="${CA_EMAIL:-}"
export CA_EMAIL

echo "[*] Distinguished Name for this root:"
echo "      C=${CA_COUNTRY}  ST=${CA_STATE}  L=${CA_LOCALITY}"
echo "      O=${CA_ORG}  OU=${CA_ORG_UNIT}  CN=${CA_COMMON_NAME}"
echo "      emailAddress=${CA_EMAIL:-<none>}"

# -----------------------------------------------------------------------------
# 1. Directory structure
# -----------------------------------------------------------------------------
mkdir -p certs crl newcerts private csr
chmod 700 private

touch index.txt
[ -f index.txt.attr ] || echo "unique_subject = yes" > index.txt.attr

# Serial/crlnumber: avoid clobbering an existing CA on re-run
[ -f serial ]    || echo 1000 > serial
[ -f crlnumber ] || echo 1000 > crlnumber

# -----------------------------------------------------------------------------
# 2. Share the DN fields that MUST match the intermediate
# -----------------------------------------------------------------------------
echo "[*] Writing ca-defaults.env (shared C/ST/L/O for the intermediate)"
cat > ca-defaults.env <<EOF
# Auto-generated by setup-root-ca.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Sourced by setup-intermediate-ca.sh — do not edit by hand, re-run
# setup-root-ca.sh instead if these values need to change.
: "\${CA_COUNTRY:=${CA_COUNTRY}}"
: "\${CA_STATE:=${CA_STATE}}"
: "\${CA_LOCALITY:=${CA_LOCALITY}}"
: "\${CA_ORG:=${CA_ORG}}"
export CA_COUNTRY CA_STATE CA_LOCALITY CA_ORG
EOF
chmod 444 ca-defaults.env

# -----------------------------------------------------------------------------
# 3. Root private key
# -----------------------------------------------------------------------------
if [ -f private/ca.key.pem ]; then
  echo "[*] Root key already exists, skipping generation"
else
  echo "[*] Generating root CA private key (4096-bit RSA, AES-256 encrypted)"
  echo "    You will be prompted for a passphrase — store it in a secrets manager, not on disk."
  openssl genrsa -aes256 -out private/ca.key.pem 4096
  chmod 400 private/ca.key.pem
fi

# -----------------------------------------------------------------------------
# 4. Root certificate (self-signed)
# -----------------------------------------------------------------------------
# -subj makes this fully non-interactive regardless of whether the
# ${ENV::...} defaults in openssl.cnf resolve to anything.
SUBJECT="/C=${CA_COUNTRY}/ST=${CA_STATE}/L=${CA_LOCALITY}/O=${CA_ORG}/OU=${CA_ORG_UNIT}/CN=${CA_COMMON_NAME}"
if [ -n "${CA_EMAIL}" ]; then
  SUBJECT="${SUBJECT}/emailAddress=${CA_EMAIL}"
fi

echo "[*] Generating self-signed root certificate (10 years, sha256)"
openssl req -new -x509 -days 3650 \
  -config "${CA_CONFIG}" \
  -subj "${SUBJECT}" \
  -key private/ca.key.pem \
  -out certs/ca.cert.pem \
  -extensions v3_ca \
  -sha256
chmod 444 certs/ca.cert.pem

echo "[*] Verifying certificate"
openssl x509 -noout -text -in certs/ca.cert.pem | head -n 20

echo
echo "[+] Root CA created at: $(pwd)"
echo "    Key:  private/ca.key.pem  (keep offline/air-gapped ideally)"
echo "    Cert: certs/ca.cert.pem"
echo
echo "Next step: intermediate CA, signed by this root."
